name: oficina_rag
channels:
  - conda-forge
dependencies:
  - python=3.11
  - faiss-cpu=1.8.0
  - ipykernel=6.29.5
  - langchain=0.2.15
  - langchain-community=0.2.15
  - langchain-core=0.2.37
  - langchain-text-splitters=0.2.2
  - openai=1.43.0
  - pypdf2=3.0.1
  - python-dotenv=1.0.1
  - jupyter
  - jupyterlab
  - pip
  - pip:
      - langchain-openai==0.1.23